version: '3.8'

services:
  master:
    build:
      context: ./master
    image: jenkins-master:latest
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home: var/jenkins_home
  
  agent:
    build:
      context: ./agent
    image: jenkins-agent:latest
    environment:
      - JENKINS_URL=http://master:8080
    depends_on:
      - master

volumes:
  jenkins_home:

networks:
  default:
    name: jenkins

