version: '3.8'

services:
  master:
    build:
      context: ./master
    image: jenkins-master:latest
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home: var/jenkins_home
  
  agent-dev:
    build:
      context: ./agent
      args:
        ENVIRONMENT: dev
    image: jenkins-agent:latest
    environment:
      - JENKINS_URL=http://master:8080
    labels:
      - "jenkins-dev"
    depends_on:
      - master
  
      
  agent-test:
    build:
      context: ./agent
      args:
        ENVIRONMENT: test
    image: jenkins-agent:latest
    environment:
      - JENKINS_URL=http://master:8080
    labels:
      - "jenkins-test"
    depends_on:
      - master

  agent-prod:
    build:
      context: ./agent
      args:
        ENVIRONMENT: prod
    image: jenkins-agent:latest
    environment:
      - JENKINS_URL=http://master:8080
    labels:
      - "jenkins-prod"
    depends_on:
      - master
      
volumes:
  jenkins_home:

networks:
  default:
    name: jenkins

